### ISSUE TITLE
Typo in README.md file

### ISSUE THREAD

**Issue by mercutioviz** [barracudanetworks/waf-automation#1]
Hi @nitzanm, this is Michael Collins using my personal github login. I've never done an issue or a pull request in github so I thought I would start small. :)

The README.md file for LetsEncrypt has a reference to the '--domains' CLI arg but in the example for doing multiple domain names it uses '--domain' (singular) instead of --domains (plural). 

Thanks,
Michael

**Comment by aravindan-barracuda** [comment]
Thank you, this is fixed.
