### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by ygagniere** [barracudanetworks/waf-automation#2]
Which version of Python are you using for the letsencrypt script because I'm having error with modules not found.

Thanks

**Comment by nitzanm** [comment]
This was written for Python 3.6, though it should be compatible with other 3.x versions of Python. Which module(s) are you seeing errors for? Have you tried installing them with pip install?

**Comment by ygagniere** [comment]
I was able to run it. But I'm still having an error. Looks like it's not able to generate a domain.key file. I get "No such file or directory": 'openssl command.

Thanks again

**Comment by nitzanm** [comment]
Ah! You do need to Have OpenSSL installed on the machine you would like to run the script on.  OpenSSL is required to generate keys, sign requests, and perform other cryptographic operations.

If you're on Linux, you can usually use your package manager to install OpenSSL (e.g. `yum install openssl` or `apt-get install openssl`).  If you're on Windows, you can download appropriate binaries from [this page](https://wiki.openssl.org/index.php/Binaries).

**Comment by ygagniere** [comment]
Hi again,

I already have openssl installed.
There's the error:

INFO:root:Parsing account key...
1 domains to process.
Traceback (most recent call last):
  File "get_certificates.py", line 106, in <module>
    main(sys.argv[1:])
  File "get_certificates.py", line 75, in main
    certificate = client.get_certificate_for_domains(args.domains, args.private_key_file, csr_file, cert_file)
  File "/home/webmaster/waf/waf-automation/waf-api/python/LetsEncrypt/utils/acme_client.py", line 402, in get_certificate_for_domains
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'openssl req -new -batch -sha256 -key domain.key -out /tmp/tmpqu71py5x -config /tmp/tmpv4r2kt79'

Thanks for you help.

**Comment by aravindan-barracuda** [comment]
Lets Encrypt support is included in the Barracuda WAF product as a built in feature now. Hence, closing this particular issue. If this still needs, please connect again.
